# Numpy

- array:
    - es un conjunto de datos de la librería numpy
    - nos recuerda a una lista
    - sólo permite 1 tipo de dato: int, float, bool, str,...
    - dimensiones: puede tener hasta n dimensiones. Lo normal es encontrarnos con hasta 3 dimensiones y para nosotras lo más usado son unidimensionales y bidimensionales

- características del array: **van sin paréntesis**
    - .shape --> nos devuelve la forma de array en forma de tupla
        - primer elemento son las matrices
        - segundo las filas
        - tercero las columnas
    - .size --> número de elementos 
    - .ndim --> número de dimensiones
    - .dtype --> tipo de dato del array

- creación de arrays:
    - np.array() --> para convertir listas en arrays
    - np.arange() --> nos permite crear arrys de una dimensión y de forma secuencial
    - np.empty() --> ojo, realmente no nos lo devuelve vacío, pone números que tiene almacenados en la memoria
    - np.zeros() --> nos crea arrays de ceros o False si ponemos el tipo de dato como bool
    - np.ones() --> 
    - np.random.randint() --> num enteros
    - np.random.rand --> 
    - np.random.random_sample --> 
**Nota sobre notación científica:**
    Se usa para poder expresar valores muy grandes o muy pequeños. Si el número tiene el formato e-5 quiere decir que tenemos que mover la coma hacia la izquierda 5 posiciones.
    Por ejemplo: 3.25149616e-01 es igual a 0.325149616

- Operaciones: ojo al hacer operaciones con arrays de distintas dimensiones
    - sumar --> + / np.add()
    - restar --> 

- Indexación:

- Filtrado



In [2]:
import numpy as np

In [20]:
array_1 = np.array([1,2,3, 4,5,6])

array_1

array([1, 2, 3, 4, 5, 6])

In [16]:
array_1.shape



(2, 3)

In [17]:
array_1.size

6

In [18]:
array_1.ndim

2

In [19]:
array_1.dtype

dtype('int64')

In [26]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
np.empty((2,3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
np.random.rand(2,3)

array([[5.55891304e-02, 3.25149616e-01, 9.74203206e-01],
       [1.07566552e-01, 6.57528465e-01, 2.86690966e-04]])

In [49]:
np.random.random_sample((2,3))

array([[0.59226812, 0.28447284, 0.90857679],
       [0.56806937, 0.28301634, 0.16062568]])

In [50]:
array_2 = np.random.randint(1,10, (2,3))
array_2

array([[5, 6, 5],
       [1, 7, 8]])

In [54]:
array_3 = np.array([5,6,7])
array_3

array([5, 6, 7])

In [57]:
array_2 + 500

array([[505, 506, 505],
       [501, 507, 508]])

In [58]:
array_4 = np.random.randint(1,10, (2,3,4))

array_4

array([[[3, 8, 4, 6],
        [7, 1, 7, 3],
        [9, 2, 2, 8]],

       [[1, 4, 3, 6],
        [9, 2, 6, 3],
        [7, 7, 5, 7]]])

In [61]:
array_4[0][0][0]

3

In [66]:
for matriz in array_4:
    for fila in matriz:
        for col in fila:



            print(col)
            print("-------------")

3
-------------
8
-------------
4
-------------
6
-------------
7
-------------
1
-------------
7
-------------
3
-------------
9
-------------
2
-------------
2
-------------
8
-------------
1
-------------
4
-------------
3
-------------
6
-------------
9
-------------
2
-------------
6
-------------
3
-------------
7
-------------
7
-------------
5
-------------
7
-------------


In [67]:
array_4

array([[[3, 8, 4, 6],
        [7, 1, 7, 3],
        [9, 2, 2, 8]],

       [[1, 4, 3, 6],
        [9, 2, 6, 3],
        [7, 7, 5, 7]]])

In [69]:
masc = array_4 > 4

In [71]:
masc

array([[[False,  True, False,  True],
        [ True, False,  True, False],
        [ True, False, False,  True]],

       [[False, False, False,  True],
        [ True, False,  True, False],
        [ True,  True,  True,  True]]])

In [70]:
array_4[masc]

array([8, 6, 7, 7, 9, 8, 6, 9, 6, 7, 7, 5, 7])

In [74]:
array_4[(array_4 > 4) & (array_4 < 9)]

array([8, 6, 7, 7, 8, 6, 6, 7, 7, 5, 7])

In [93]:
np.where(array_4 > 4, array_4, 0)

array([[[0, 8, 0, 6],
        [7, 0, 7, 0],
        [9, 0, 0, 8]],

       [[0, 0, 0, 6],
        [9, 0, 6, 0],
        [7, 7, 5, 7]]])

In [95]:
array_5 = np.where((array_4 > 4) & (array_4 < 9), array_4, 0)

array_5

array([[[0, 8, 0, 6],
        [7, 0, 7, 0],
        [0, 0, 0, 8]],

       [[0, 0, 0, 6],
        [0, 0, 6, 0],
        [7, 7, 5, 7]]])

In [84]:
array_4

array([[[3, 8, 4, 6],
        [7, 1, 7, 3],
        [9, 2, 2, 8]],

       [[1, 4, 3, 6],
        [9, 2, 6, 3],
        [7, 7, 5, 7]]])

In [89]:
array_str = np.where(array_4 < 4,"A",  np.where(array_4 < 9, "B", "C"))

In [90]:
array_str

array([[['A', 'B', 'B', 'B'],
        ['B', 'A', 'B', 'A'],
        ['C', 'A', 'A', 'B']],

       [['A', 'B', 'A', 'B'],
        ['C', 'A', 'B', 'A'],
        ['B', 'B', 'B', 'B']]], dtype='<U1')